import ButtonProposal from '@/components/ui/proposal/Button'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='font-family-georgia'> Proposal </h1>

        <div className='w-64'>
          <ButtonProposal 
            color="primary"
            size="large"
            text="View contract"
          />
        </div>
      </main>
    </>
  )
}
