import LayoutSidebar from '@/components/proposal/LayoutSidebar'
import LayoutContent from '@/components/proposal/LayoutContent'
import Sidebar from '@/components/proposal/Sidebar'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='min-w-screen max-w-screen flex'>
        {/* Sidebar */}
        <LayoutSidebar>
          <Sidebar />
        </LayoutSidebar>

        {/* -------- */}

        {/* Content */}
        <LayoutContent>
          
        </LayoutContent>
      </div>
    </>
  )
}
